iptables/builder/builder.go, iptables/builder/builder_nat.go, iptables/builder/builder_raw.go, iptables/config/config.go
As we have to disable dns conntrack zone splitting for the e2e tests in kuma, this change allows us to disable it via config
=> feat: allow disabling dns conntrack zone split

go.sum, iptables/builder/builder.go, iptables/builder/builder_mangle.go, iptables/config/config.go, iptables/parameters/jump.go, iptables/parameters/match/conntrack/conntrack.go, iptables/parameters/match_conntrack.go, iptables/parameters/match_conntrack_test.go, iptables/table/table_mangle.go
Sometimes (especially in high traffic scenarios) it is possible
that tcp connections would receive packets in invalid state, and
we would like the connection to stay alive and just to drop
this packet.
As to introduce blackbox test for this scenario we would have to:
- manually construct tcp packets to carry out three way tcp
handshake
- trick kernel (who woundn't know about our TCP connection and
wound RST the connection immidiately after SYN) to let our
"forged" connection to be
- make and send some invalid packets, in scenario without this flag
(connection should be closed) and with the flag enabled
(connection should stay alive and the packets should be DROPped)
which involves a lot of effort and time, I decided to potentially
do it in following up tasks
Closes: …
=> feat: add option to drop invalid packets

iptables/parameters/destination.go, iptables/parameters/destination_test.go
Changed flags of destination parameter from `-s` and `--source`
to `-d` and `--destination` as well as written unit tests
to make sure, this mistake won't happen again for this parameter
=> fix: destination parameter had wrong strings

iptables/builder/builder_nat.go, iptables/builder/builder_raw.go, iptables/config/config.go
Removing GID related iptable rules which simplifies the whole rules set
+ added one convenience function to the config struct
Closes: https://github.com/kumahq/kuma-net/issues/28
=> feat: get rid of GID related iptable rules

test/framework/netns/builder.go
When configuring network namespace with IPv6 addresses, on some
machines when sending requests immediately after configuring netns
they are time-outing, when on others there is 1-2s delay before
receiving the response.
I was able to narrow down the cause to be related to
IPv6 neighbor discovery, but was not able to find a real reason
or a fix, so we have to introduce this delay.
The other observation I got is when sending requests
immediately, they are going through ens5/eth0 interface instead of
created by us veth main one
=> fix: timeouting ipv6 tests on some machines fix

iptables/config/config.go
Enable DNS conntrack zone splitting in config by default
=> chore: enable by default dns conntrack zone split

iptables/builder/builder_nat.go, iptables/config/config.go, test/blackbox_tests/inbound_redirect_test.go
As in kuma we are using specific listeners/clusters for IPv6
inbound traffic, this changes allow to specify port to allow this
Closes: https://github.com/kumahq/kuma-net/issues/47
=> feat: introduce inbound ipv6 redirect port (15010)

iptables/builder/builder_raw.go, iptables/config/config.go
Added logic to validate if there is `conntrack` iptables extension
available, before applying dns conntrack zone splitting related
rules. If it's not available (WSL2), then print warning and move
forward.
=> feat: dns conntrack rules when extension available

.github/workflows/tests.yaml, firewalld/firewalld.go, firewalld/firewalld_suite_test.go, firewalld/firewalld_test.go, firewalld/testdata/full_direct.golden.xml, firewalld/testdata/full_direct.input.txt, firewalld/testdata/full_direct_verbose.golden.xml, firewalld/testdata/full_direct_verbose.input.txt, firewalld/testdata/no_duplicates_direct.golden.xml, firewalld/testdata/no_duplicates_direct.input.txt, firewalld/xml.go, test/framework/golden/update_files.go, test/framework/gomega_matchers/golden.go
Move firewalld related logic from `kumahq/kuma` to
`kumahq/kuma-net`.
As we are supporting longer - verbose commands and flags, I had to
modify a little bit existing firewalld logic as well as update
tests, which made it more error proof and robust.
Updated CI to run firewalld tests
ref. https://github.com/kumahq/kuma-net/issues/54 (will close the issue when changes in `kumahq/kuma` will be merged)
=> feat: move firewalld from kuma to kuma-net

iptables/builder/builder_nat.go, iptables/config/config.go, test/blackbox_tests/inbound_redirect_test.go, test/blackbox_tests/outbound_redirect_test.go
Added option to configure ports that are redirected by `iptables` and only them.
Fix #30
=> feat(*): added ability to include only specific ports in tp rules

ebpf/ebpf.go, ebpf/setup.go, ebpf/setup_fallback.go, go.mod, go.sum, iptables/builder/builder.go, iptables/builder/builder_mangle.go, iptables/builder/builder_nat.go, iptables/builder/builder_raw.go, iptables/setup.go, test/blackbox_tests/dns_test.go, test/blackbox_tests/inbound_redirect_test.go, test/blackbox_tests/outbound_redirect_test.go, transparent-proxy/config/config.go, transparent-proxy/setup.go
- Added code which allows to use ebpf instead of iptables
  to configure transparent proxy
- Added ebpf related configuration fields to our config struct
- Created another abstraction which allows to wrap iptables and
  ebpf "configurators", which allows to remove some code from
  the kuma repository responsible for generation of iptables
  rules. Now this wrapper is available under `transparent-proxy`
  directory, and depending on configuration, it will call ebpf
  or iptables respectively
- Moved from kuma codebase some logs displayed when installing
  transparent proxy using iptables, which allows us to have
  greater control of what's being logged and when
- Moved out configuration from iptables directory to more
  appropriate place (created earlier `transparent-proxy` directory)
  as …
=> feat: add logic to use ebpf for tproxy

.github/workflows/build.yaml, .github/workflows/release.yaml, tools/builds/dockerfiles/Dockerfile.kuma-net-ebpf, tools/builds/dockerfiles/Dockerfile.kuma-net-ebpf.dockerignore, tools/builds/ebpf/compile.mk, tools/builds/ebpf/load-and-attach.mk
Instead of including logic to work with merbridge/ebpf docker images we should do it inside kuma-net, so this PR introduces the logic and configuration for github actions to build and publish `kumahq/kuma-net-ebpf` docker image
=> feat: build and publish kuma-net-ebpf docker image

iptables/builder/builder.go
Configs (default and user provided) were not merged before DNS servers check
=> fix: merge tproxy config before dns servers check

ebpf/setup.go, ebpf/tc.go, go.mod, go.sum
The introduced by this changes logic allows kuma to attach tc ebpf programs in init containers which solves a tone of problems (mtls bypassing, not working virtual probles, not being able to exclude ports via annotations and more)
=> feat: introduce ebpf tc programs

iptables/builder/builder_nat.go, iptables/consts/consts.go, iptables/parameters/jump.go, test/blackbox_tests/inbound_redirect_test.go, test/blackbox_tests/outbound_redirect_test.go, transparent-proxy/config/config.go
Added the possibility to define iptables rules for logging. Because of https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=69b34fb996b2eee3970548cf6eb516d3ecb5eee  logging from a namespace is not available in system logs. I've added an option to enable iptables logs to a few tests to check if rules are not breaking applying of rules. Also, I didn't add an insert on the first place to not put them in front of the user rules.
Fix #31
=> feat(*): added logging rule to the iptables

ebpf/cleanup_fallback.go
It makes it consistent with `.Setup(...)` function and is necessary to not break CI in kuma
=> chore(ebpf): add cleanup fallback - non-linux arch

tools/builds/dockerfiles/Dockerfile.kuma-net-ebpf
`BASE_IMAGE_ARCH` was set to amd64 all the time. Removed it now buildx should provide the correct value.
ref #96
=> chore(*): removed platform because buildx does it for us

ebpf/ebpf.go
After changes in https://github.com/kumahq/merbridge/pull/5 we do not need to cleanup map anymore
=> fix(ebpf): removed net cleanup script which is not used anymore

tools/builds/dockerfiles/Dockerfile.kuma-net-ebpf
Put ebpf programs in docker image to `/ebpf/` directory instead of `/`
=> chore(ebpf): put ebpf programs in image to /ebpf/

iptables/builder/builder_nat.go, iptables/builder/builder_nat_test.go, iptables/builder/builder_suite_test.go, iptables/chain/chain.go, iptables/commands/command.go
Docker vnet rules need to be at the beginning of PREROUTING chain. Docker adds the rule which redirects all traffic and in case we won't insert them at the beginning traffic doesn't reach a sidecar.
=> fix(tp): insert docker vnet rules at the begining of PREROUTING chain

iptables/builder/builder_nat.go
Because of order of iptables in docker, it might starts to fails if iptables rules are not the first one. Changed previous behaviour(append) to inserts.
=> fix(iptables): changed append to insert for dns
